apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: packersmovers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: packersmovers
  template:
    metadata:
      labels:
        app: packersmovers
    spec:
      containers:
      - name: customer
        image: 703550360617.dkr.ecr.ap-south-1.amazonaws.com/batch13:latest
        imagePullPolicy: Always
